[workspace.package]
version = "1.3.3"
authors = [
    "SmileSky <mzdk100@foxmail.com>",
    "The Rust Windowing contributors",
]
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["android", "ndk", "apk"]
repository = "https://github.com/mzdk100/cargo-apk2.git"
rust-version = "1.90.0"

[workspace.dependencies]
android-activity = "0.6.0"
android-build = { version = "0.1.3", default-features = false }
android_logger = "0.15.1"
anyhow = "1.0.100"
cargo-subcommand = "0.12.0"
clap = "4.5.54"
dirs = "6.0.0"
dunce = "1.0.5"
env_logger = "0.11.8"
jni = "0.21.1"
libc = "1.0.0-alpha.2"
log = "0.4.29"
ndk = "0.9.0"
ndk-context = "0.1.1"
quick-xml = "0.38.4"
serde = "1.0.228"
thiserror = "2.0.17"
toml = "0.9.10+spec-1.1.0"
which = "8.0.0"

[workspace]
members = [
    "groovy-examples",
    "java-examples",
    "kotlin-examples",
    "scala-examples",
    "ndk-build2",
    "ndk-examples",
    "cargo-apk2",
]
resolver = "3"
